AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  signal-spotter-apis

  All APIs and Lambdas for Signal Spotter application.

Resources:
  PublishLambdaFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: functions/PublishLambdaFunction
      Timeout: 10
      Handler: publishlambda.App::handleRequest
      Runtime: java8
      MemorySize: 512
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1 # More info about tiered compilation https://aws.amazon.com/blogs/compute/optimizing-aws-lambda-function-performance-for-java/
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /publish
            Method: get

  RecieveLambdaFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: functions/RecieveLambdaFunction
      Timeout: 10
      Policies:
      - AWSLambdaExecute
      - AmazonDynamoDBFullAccess

      Handler: recievelambda.App::handleRequest
      Runtime: java8
      MemorySize: 512
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1 # More info about tiered compilation https://aws.amazon.com/blogs/compute/optimizing-aws-lambda-function-performance-for-java/
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /recieve
            Method: get

  TransactionTable:
    Type: AWS::Serverless::SimpleTable # More info about SimpleTable Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-simpletable.html
    Properties:
      PrimaryKey:
        Name: Id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TableName: wifi-map-csusm

Outputs:
  PublishAPI:
    Description: "API Gateway endpoint URL for Prod stage for publish function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/publish/"

  RecieveAPI:
    Description: "API Gateway endpoint URL for Prod stage for recieve function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/recieve/"

  PublishLambdaFunction:
    Description: "Publish Lambda Function ARN"
    Value: !GetAtt PublishLambdaFunction.Arn

  RecieveLambdaFunction:
    Description: "Recieve Lambda Function ARN"
    Value: !GetAtt RecieveLambdaFunction.Arn

  PublishLambdaFunctionIamRole:
    Description: "Implicit IAM Role created for Publish Lambda function"
    Value: !GetAtt PublishLambdaFunctionRole.Arn

  RecieveLambdaFunctionIamRole:
    Description: "Implicit IAM Role created for Recieve Lambda function"
    Value: !GetAtt RecieveLambdaFunctionRole.Arn
